### ISSUE TITLE
Initial pages for the new oceanbuilders.com website

### ISSUE THREAD

**Issue by diegopau** [oceanbuilders/ob-website#1]
- Cruise ship page 1 (https://www.dropbox.com/s/rfl3d7749imujyx/Screen%20Shot%202020-10-17%20at%2020.39.16.png?dl=0)
- When people register for the form on (https://ocean.builders/cruiseship/) it should go to the same mailchimp list that it goes to currently in our mailchimp account (you can probably pull that info from our wordpress account for ocean.builders on that page)
- SeaPod page 1 (https://www.dropbox.com/s/coacice9v2l038m/Screen%20Shot%202020-10-17%20at%2020.39.35.png?dl=0)
- Media page: https://www.dropbox.com/s/vzksebz0kxlx8dh/Screen%20Shot%202020-10-17%20at%2020.28.05.png?dl=0
- Contact page: https://www.dropbox.com/s/6iwqzb1azjvrp9e/Screen%20Shot%202020-10-17%20at%2020.27.33.png?dl=0
- Email Sign up: https://www.dropbox.com/s/cbxq1k1jekqgxyd/Screen%20Shot%202020-10-17%20at%2020.41.53.png?dl=0
- Cruise Ship pages (all other pages after the first page)

**Comment by diegopau** [comment]
- FAQ (Grant will provide it in around 2 days)
- Auction page
- Incubator page
- SSL certificate

**Comment by diegopau** [comment]
MailChimp integration

**Comment by diegopau** [comment]
New requirement from Grant about payments:

ll payments will be taken by either Stripe, Wire transfer, PayPal or Coinpayments. I will have a guy from coinpayments help us with configuring the set up (Maybe I'll have them walk me through that on a call). I think if we use something like woocommerce plugin it should give us a lot of flexibility. I know Coinpayments integrates with them and I'm sure the others services will plug in easily as well.

The process will be that:
1. people go to the auction page.
2. they have an option to buy now at a specific price. If they opt for that then we need to bill them $100 upfront by either payment option (stripe/paypal/coinpayments). There will be additional payments needed in the future but maybe we should just focus on the initial payment. I think this shouldn't be too hard for configuration.
3. no payments needed on bidding on a room until auction closes.

**Comment by scottdear** [comment]
@angiedear it looks like this issue needs some grooming and should be split into multiple issues.  Also @olagalal and @Mikisson can we get a status update as to where this is currently and what is outstanding.

**Comment by angiedear** [comment]
Is this an old issue?  Does it need to be closed?

**Comment by Mikisson** [comment]
Yes it is! It's done.
you can close it. 😎

[image: photo]
Miki Uhelja
Content Manager
E ***@***.***  ***@***.***> W  ScissorBoy.com
<http://link.wisestamp.com/wf/click?upn=3OEiqGYCeh5Ed8dQkQvaYDniJn4UpnjMHduu1TTTITk-3D_-2FlDaUasMvGgjFTu9fHupdSn4yScG22R6ztxDd6Cp-2FDRF3Op-2Bx-2FhlZ-2Bg3QyP6OZxL-2Bel-2BGInyz9JdOOLEwsRXR8xQwELH7-2BTnHPE5s64F1pTshYdXTjQDCKe8OCogbWPsnkncG9RFJVwmLXNORN-2BPlzQ5-2BgwGICGMNIISJujOJUZAJlmMEVGGtztCIVlE3gRMdeKPr2dNVlAbfb-2B2fe-2FMOuELrHUvInDfEzHDE093wXr5VWm33TyNvSsZr25mH2-2BFbr4JkxS7oQbQC-2BmJjwW2Ug-3D-3D>
W  TheMasteryApp.com
<http://link.wisestamp.com/wf/click?upn=0Q6ghz5zSp7IP-2F3wyuFgZ5NdeY5s0IyyVD2HuaOtgj8-3D_-2FlDaUasMvGgjFTu9fHupdSn4yScG22R6ztxDd6Cp-2FDRF3Op-2Bx-2FhlZ-2Bg3QyP6OZxLMLlfDPPbfQe8sn-2FcYi7ieLV52n7kmUxD16djsbUTqQKa3SsAMFxbXw7AApkzirJy5G-2Bn2yWxVZC7wY8T83ce-2FHwzuItiNwL0bF-2FsGAdNjPTqmK5eG3K1AS3o8ILijR33ejY91BP29dzHH5PrZ-2BKf9XFOy-2F7F-2FFaAo3W-2Bq7J9qtzV1i157uFtC3O8gAb7YyW6ZyfNXCXUQVw1fGSEzg8VsA-3D-3D>

<http://www.facebook.com/cosmetology.education.scissorboy/>
<http://twitter.com/thescissorboy> <http://www.linkedin.com/in/scissorboy>
<http://www.quora.com/profile/Grant-Romundt>

**Comment by angiedear** [comment]
Thanks Miki!
